In [1]:
import numpy as np
from numpy import random

In [41]:
# generating a integer
x = random.randint(100)

print(x)

26


In [43]:
# generating a float
# Generate a random float from 0 to 1:

x = random.rand()

print(x)

0.5163161640972546


In [44]:
x=random.randint(100, size=(5))

print(x)

[90  2 24 17 75]


In [45]:
x = random.randint(100, size=(3, 5))

print(x)

[[35 28 70 13 62]
 [71 74 12 51 94]
 [71 75  9 42  9]]


In [46]:
x = random.rand(5)

print(x)

[0.03944793 0.6869858  0.90264634 0.28737525 0.51147853]


In [47]:
x = random.rand(3, 5)

print(x)

[[0.98729625 0.72879488 0.10647296 0.15558191 0.94214447]
 [0.2252054  0.25592863 0.30760612 0.00133919 0.78277941]
 [0.16340696 0.18425575 0.49313051 0.74848247 0.35490355]]


In [48]:
x = random.choice([3, 5, 7, 9])

print(x)

5


In [49]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 9 7 3 3]
 [7 5 7 5 9]
 [5 5 7 9 7]]
